# Generated by Django 6.0.6 on 2026-06-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
