# Generated by Django 6.0.6 on 2026-06-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='dealers/'),
        ),
    ]
