# Generated by Django 6.0.6 on 2026-06-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_dealerprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarClickAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('view_details', 'View Details'), ('whatsapp', 'WhatsApp'), ('call', 'Call Dealer')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='cars.car')),
            ],
            options={
                'verbose_name_plural': 'Car click analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['car', 'click_type', '-created_at'], name='cars_carcli_car_id_9b12d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(db_index=True, max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('matched_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='cars.car')),
            ],
            options={
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['matched_car', '-searched_at'], name='cars_carsea_matched_67e157_idx'), models.Index(fields=['search_keyword', '-searched_at'], name='cars_carsea_search__be819b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cars.car')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['car', '-viewed_at'], name='cars_carvie_car_id_91483f_idx'), models.Index(fields=['visitor_ip', '-viewed_at'], name='cars_carvie_visitor_3bf26d_idx')],
            },
        ),
    ]
